-- Create the Enum for Staff Roles
create type staff_role as enum ('Junior', 'Intermediate', 'Senior');

-- Create the Staff table
create table staff (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  role staff_role not null default 'Intermediate'::staff_role,
  default_target_shifts integer not null default 7
);

-- Optional: Add some initial data (Policy: Allow public read/write for this demo app)
-- Note: For production, you should enable RLS (Row Level Security) and configure proper policies.
alter table staff enable row level security;

create policy "Enable read access for all users"
on staff for select
using (true);

create policy "Enable insert access for all users"
on staff for insert
with check (true);

create policy "Enable update access for all users"
on staff for update
using (true);

create policy "Enable delete access for all users"
on staff for delete
using (true);

